allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract

minimumReleaseAgeExclude:
  - '@analogjs/platform@2.6.0'
  - '@analogjs/vite-plugin-angular@2.6.0'
  - '@analogjs/vite-plugin-nitro@2.6.0'
  - '@angular-devkit/architect@0.2200.0'
  - '@angular-devkit/core@22.0.0'
  - '@angular-devkit/schematics@22.0.0'
  - '@angular/animations@22.0.0'
  - '@angular/build@22.0.0'
  - '@angular/cdk@22.0.0'
  - '@angular/cli@22.0.0'
  - '@angular/common@22.0.0'
  - '@angular/compiler-cli@22.0.0'
  - '@angular/compiler@22.0.0'
  - '@angular/core@22.0.0'
  - '@angular/forms@22.0.0'
  - '@angular/platform-browser@22.0.0'
  - '@angular/router@22.0.0'
  - '@schematics/angular@22.0.0'
  - jscpd@5.0.4
  - '@typescript-eslint/eslint-plugin@8.61.0'
  - '@typescript-eslint/parser@8.61.0'
  - '@typescript-eslint/project-service@8.61.0'
  - '@typescript-eslint/scope-manager@8.61.0'
  - '@typescript-eslint/tsconfig-utils@8.61.0'
  - '@typescript-eslint/type-utils@8.61.0'
  - '@typescript-eslint/types@8.61.0'
  - '@typescript-eslint/typescript-estree@8.61.0'
  - '@typescript-eslint/utils@8.61.0'
  - '@typescript-eslint/visitor-keys@8.61.0'
  - typescript-eslint@8.61.0
  - angular-cli-ghpages@3.1.0

onlyBuiltDependencies:
  - cypress
