allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract

onlyBuiltDependencies:
  - cypress
